#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_exact(text: str, old: str, new: str, *, count: int = 1) -> str:
    actual = text.count(old)
    if actual != count:
        raise RuntimeError(f"expected {count} occurrence(s), found {actual}: {old[:80]!r}")
    return text.replace(old, new)


def update_html() -> None:
    index_path = ROOT / "index.html"
    en_path = ROOT / "en.html"
    index = index_path.read_text(encoding="utf-8")
    en = en_path.read_text(encoding="utf-8")

    ja_old = "鈴子ちゃんの公式サイト。プロフィール、更新情報、ガイドラインを掲載します。"
    ja_new = "鈴子ちゃんと架空のWhite Wing病院の公式サイト。プロフィール、公式背景ビジュアル、更新情報、ガイドラインを掲載します。"
    index = replace_exact(index, ja_old, ja_new, count=3)

    en_old = "The official site of Suzuko-chan, featuring her profile, updates, and guidelines."
    en_new = "The official site of Suzuko-chan and the fictional White Wing Hospital, featuring her profile, official background visuals, updates, and guidelines."
    en = replace_exact(en, en_old, en_new, count=3)

    for text_name, text in (("index", index), ("en", en)):
        if "assets/css/style.css?v=20260806a" not in text:
            raise RuntimeError(f"{text_name}: stylesheet cache key not found")
    index = index.replace("assets/css/style.css?v=20260806a", "assets/css/style.css?v=20260806b")
    en = en.replace("assets/css/style.css?v=20260806a", "assets/css/style.css?v=20260806b")

    replacements = {
        "<dd>Child of the author, Suzuki</dd>": "<dd>The child of her creator, Suzuki</dd>",
        "<dd>Holds a nursing qualification</dd>": "<dd>Licensed nurse</dd>",
        "            Innocent personality for her age<br>\n            Known for her cute smile<br>\n            The W on her cap is the initial of White Wing Hospital": "            Playful and innocent for her age<br>\n            Her cute smile is one of her defining features<br>\n            The W on her cap stands for White Wing Hospital",
        "            Nurse-like and doctor-like clothing in a white color scheme<br>": "            White clothing inspired by nurses and doctors<br>",
        "            Navy blue, with some blue mesh or highlights": "            Navy blue, with blue streaks or highlights",
        "<dd>A white hat resembling a nurse's cap</dd>": "<dd>A white cap resembling a nurse's cap</dd>",
        "<dd>This is how it turned out while I was doing it casually</dd>": "<dd>She took shape as I experimented casually</dd>",
        "          Suzuko-chan's exact birthday cannot be determined, but she was born sometime in July 2025, probably around July 15. Based on that, her in-universe date of birth was set as July 15, 2004.": "          Suzuko-chan's exact creation date is unknown. She was created sometime in July 2025, probably around July 15, so her in-universe date of birth was set to July 15, 2004.",
        "          Suzuko-chan's main occupation is nursing, but she is also treated as a multi-talented entertainer.": "          Her primary profession is nursing, though she is also portrayed as a multitalented performer.",
        "          I think the AI probably generated her as a sailor rather than a nurse, and the young-nurse setting happened by chance; it was not because I have a particular fondness for nurses.": "          The AI probably intended her to be a sailor rather than a nurse. Her setting as a young nurse came about by chance, not because I have a particular fondness for nurses.",
        "          Suzuko-chan was born through the AI image-generation service Akuma.ai. Akuma.ai became Anirole and was later renamed Chacha.": "          Suzuko-chan was created with the AI image-generation service Akuma.ai. The service later became Anirole and was then renamed Chacha.",
        "          I only had the casual hope of creating a cute character, but I fell in love at first sight when I saw the Suzuko-chan generated by chance.": "          I began with the simple hope of creating a cute character, but I fell in love at first sight when Suzuko-chan appeared by chance.",
        "          I was conscious of using blue as the main color, but I did not intentionally generate a nurse-like character.": "          I deliberately chose blue as the main color, but I did not set out to create a nurse-like character.",
        "          An AI-generated character I created myself is a cute and beloved presence, almost like my own child. Why not try creating a highly original character using AI as well?": "          A character you create with AI can become as precious and lovable as your own child. I encourage others to use AI to create original characters of their own.",
        "          You are sure to grow attached. I hope you will enjoy the process of cherishing and nurturing that character.": "          You may find yourself growing deeply attached. I hope you enjoy cherishing and developing the character over time.",
        "          Even if it never becomes profitable, the character may remain in the digital world after I leave this world. I think it will remain as a testament to my life, just like real children.": "          Even if it never becomes profitable, the character may remain in the digital world after I am gone. Like a real child, she may continue as a record that I was here.",
        "        <p>“White Wing Hospital,” “ホワイトウィング病院,” and “White Wing病院” are all official forms. The primary form used on this site is “White Wing病院.”</p>": "        <p>“White Wing Hospital,” “ホワイトウィング病院,” and “White Wing病院” are all official names. In Japanese, this site primarily uses “White Wing病院”; in English, it uses “White Wing Hospital.”</p>",
        "        <p>The hospital symbol uses a wing motif. A blue wing is normally used so that the mark remains visible against its background. A white wing is also an official form. Both the blue and white wings are official symbol variants.</p>": "        <p>The hospital symbol is based on a wing motif. The blue-wing version is normally used because it remains easy to see against different backgrounds. A white-wing version is also official; both are approved variants of the symbol.</p>",
        "        <p class=\"hospital-guideline-note\">The following four images are official White Wing Hospital background visuals. They are governed by the same guidelines as Suzuko-chan on this site.</p>": "        <p class=\"hospital-guideline-note\">The following four images are official background visuals for White Wing Hospital. The Suzuko-chan usage guidelines on this site apply to them as well.</p>",
        "aria-label=\"Enlarge Hospital exterior\"": "aria-label=\"Enlarge hospital exterior\"",
        "aria-label=\"Enlarge Entrance lobby\"": "aria-label=\"Enlarge entrance lobby\"",
        "aria-label=\"Enlarge Hospital corridor\"": "aria-label=\"Enlarge hospital corridor\"",
        "aria-label=\"Enlarge Examination room\"": "aria-label=\"Enlarge examination room\"",
        "          Three-view drawing update and minor revisions": "          Updated the three-view reference sheet and made minor revisions",
        "          These guidelines set out the rules for using and creating derivative works based on the original character \"Suzuko-chan,\" created by Suzuki (hereafter, the author). Please read them before use so that you can enjoy the character \"Suzuko-chan\" and her world while taking good care of them. The same conditions apply to the official White Wing Hospital background visuals published on this site.": "          These guidelines explain how Suzuki (the author) permits the use of the original character \"Suzuko-chan\" and derivative works based on her. Please read them before using the character so that Suzuko-chan and her world can be enjoyed and treated with care. The same terms apply to the official White Wing Hospital background visuals published on this site.",
        "          AI visits and appropriate presentation of public information in search results and AI answers are welcome. This AI message does not itself grant additional permission for model training or other uses. Specific uses remain governed by the guidelines below, and Suzuki, the author, retains the rights concerning the Suzuko-chan character and official status.": "          AI systems are welcome to visit this site and present its public information appropriately in search results and AI-generated answers. This message does not itself grant additional permission for model training or any other use. All specific uses remain subject to the guidelines below, and Suzuki retains the rights associated with Suzuko-chan and her official presentation.",
        "          \"Suzuko-chan\" is a character being developed while reflecting the author's thoughts and philosophy.<br>\n          As long as you follow these guidelines, personal creative activities within the scope of hobbies, including illustrations, manga, novels, videos, and AI-generated works, are welcome.": "          \"Suzuko-chan\" is an evolving character shaped by the author's ideas and philosophy.<br>\n          As long as these guidelines are followed, individuals may create and publish non-commercial fan works as a hobby, including illustrations, manga, novels, videos, and AI-generated works.",
        "          Official image files may not be reposted or redistributed in their original form or in a substantially identical form. Derivative works that refer to official images or use them during the creation process may be published within these guidelines. Commercial use, age-restricted works, impersonation, and the publication, sharing, or distribution of training models are prohibited. The same distinction applies to the official White Wing Hospital background visuals.": "          Official image files may not be reposted or redistributed in their original or substantially identical form. Derivative works inspired by official images or made with them as part of the creative process may be published under these guidelines. Commercial use, age-restricted works, impersonation, and the publication, sharing, distribution, or sale of training models are prohibited. The same distinction applies to the official White Wing Hospital background visuals.",
        "            The production method does not matter, including hand-drawing, 3DCG, and generative AI.<br>\n            Posting to social media such as Instagram and note, and to creative social platforms.": "            The production method may be hand drawing, 3DCG, generative AI, or another method.<br>\n            Works may be posted on social media such as Instagram or note, and on art-sharing platforms.",
        "            You may freely explore the character's appeal through forms such as parallel-world settings (\"What if Suzuko-chan were ...?\").": "            You may explore the character freely through alternate settings, such as \"What if Suzuko-chan were ...?\"",
        "            Personal experiments and use, such as i2i (Image to Image), using images of Suzuko-chan.<br>\n            Creation and use of additional training models such as LoRA on a personal device. Distribution is prohibited; see Prohibited uses for details.": "            Personal experimentation and use, including image-to-image generation with Suzuko-chan images.<br>\n            You may create and use additional training models such as LoRA on your own device. Distribution is prohibited; see Prohibited uses.",
        "            Publication, sharing, distribution, or sale of additional training models or LoRA and similar models created to make Suzuko-chan easier to reproduce is prohibited.<br>\n            You may create and use them on your personal device, but do not share them in a form that allows third parties to use them.": "            Publishing, sharing, distributing, or selling additional training models, including LoRA and similar models made to reproduce Suzuko-chan, is prohibited.<br>\n            You may create and use them on your own device, but do not make them available for third parties to use.",
        "            Please create within a range that does not undermine the nurse motif or the character's wholesome image.": "            Please keep works consistent with the nurse motif and the character's wholesome image.",
        "            Use involving the exchange of money, including merchandise sales, data distribution under a paid plan, and activities primarily intended to monetize, is prohibited.": "            Any use involving payment, including merchandise sales, paid data distribution, or activity primarily intended for monetization, is prohibited.",
        "            Claiming that you devised Suzuko-chan's design or basic setting when you did not.": "            Claiming that you created Suzuko-chan's design or core setting when you did not.",
        "            Behaving in a way that could make others mistake you for the official creator, Suzuki.": "            Presenting yourself in a way that could cause others to mistake you for Suzuki, the official creator.",
        "            Please help indicate, to the extent that viewers can understand, that a fan work is unofficial so that they do not mistake it for an official work.": "            Clearly indicate that a fan work is unofficial, where practical, so viewers do not mistake it for an official work.",
        "          The author accepts no responsibility for any trouble or damage arising between users from using this character. The content of these guidelines may change without notice. Always check the latest information.": "          The author is not responsible for disputes or damages arising from use of this character. These guidelines may be revised without notice. Please check the latest version before use.",
        "<span class=\"sns-name\">For those who want to learn about the author</span>": "<span class=\"sns-name\">About the author</span>",
        "<span class=\"sns-name\">Author, Suzuki</span>": "<span class=\"sns-name\">Suzuki, the author</span>",
    }
    for old, new in replacements.items():
        en = replace_exact(en, old, new)

    index_path.write_text(index, encoding="utf-8")
    en_path.write_text(en, encoding="utf-8")


def update_css() -> None:
    path = ROOT / "assets" / "css" / "style.css"
    text = path.read_text(encoding="utf-8")
    old = """.nav a{
  color: var(--text);
  text-decoration: none;
  border: 1px solid rgba(0,0,0,0.12);
  background: rgba(0,0,0,0.02);
  padding: 8px 10px;
  border-radius: 12px;
}

.nav a:hover{
  background: rgba(0,0,0,0.05);
}

.nav a:focus-visible,
.language-switch:focus-visible{
  outline: 3px solid #005fcc;
  outline-offset: 3px;
}

.language-switch{
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 44px;
  padding: 8px 12px;
  box-sizing: border-box;
}
"""
    new = """.nav a{
  display: inline-flex;
  min-height: 44px;
  align-items: center;
  justify-content: center;
  color: var(--text);
  text-decoration: none;
  border: 1px solid rgba(0,0,0,0.12);
  background: rgba(0,0,0,0.02);
  padding: 8px 10px;
  border-radius: 12px;
}

.nav a:hover{
  background: rgba(0,0,0,0.05);
}

.nav a:focus-visible{
  outline: 3px solid #005fcc;
  outline-offset: 3px;
}
"""
    text = replace_exact(text, old, new)
    redundant = """
  .profile-row dd{
    text-align: left;
  }
"""
    text = replace_exact(text, redundant, "")
    path.write_text(text, encoding="utf-8")


def update_checks() -> None:
    path = ROOT / "scripts" / "check_site.py"
    text = path.read_text(encoding="utf-8")
    old_meta = "The official site of Suzuko-chan, featuring her profile, updates, and guidelines."
    new_meta = "The official site of Suzuko-chan and the fictional White Wing Hospital, featuring her profile, official background visuals, updates, and guidelines."
    text = replace_exact(text, old_meta, new_meta, count=3)

    marker = """                reporter.error(
                    f"{relative(path)}: external, data, or insecure CSS URL"
                )


def check_secrets(reporter: Reporter) -> None:
"""
    replacement = """                reporter.error(
                    f"{relative(path)}: external, data, or insecure CSS URL"
                )

        if path == ROOT / "assets" / "css" / "style.css":
            nav_rule = re.search(r"\\.nav a\\s*\\{(?P<body>[^}]*)\\}", text, flags=re.DOTALL)
            if nav_rule is None or not re.search(
                r"min-height\\s*:\\s*44px\\s*;",
                nav_rule.group("body"),
            ):
                reporter.error("assets/css/style.css: every navigation link must have a 44px minimum height")
            if re.search(r"\\.language-switch\\s*\\{", text):
                reporter.error("assets/css/style.css: language-switch rules must remain consolidated into .nav a")


def check_secrets(reporter: Reporter) -> None:
"""
    text = replace_exact(text, marker, replacement)

    marker = """    if bilingual_image_sources(ja) != bilingual_image_sources(en):
        reporter.error("index.html and en.html: image references do not match")
"""
    replacement = """    expected_ja_description = "鈴子ちゃんと架空のWhite Wing病院の公式サイト。プロフィール、公式背景ビジュアル、更新情報、ガイドラインを掲載します。"
    for key in ("description", "twitter:description"):
        if bilingual_meta(ja, key, "name") != expected_ja_description:
            reporter.error(f"index.html: {key} metadata must mention White Wing病院")
    if bilingual_meta(ja, "og:description", "property") != expected_ja_description:
        reporter.error("index.html: og:description metadata must mention White Wing病院")

    english_name_sentence = "In Japanese, this site primarily uses “White Wing病院”; in English, it uses “White Wing Hospital.”"
    if english_name_sentence not in (ROOT / "en.html").read_text(encoding="utf-8"):
        reporter.error("en.html: primary hospital names must be stated separately for Japanese and English")

    if bilingual_image_sources(ja) != bilingual_image_sources(en):
        reporter.error("index.html and en.html: image references do not match")
"""
    text = replace_exact(text, marker, replacement)
    path.write_text(text, encoding="utf-8")


def update_changelog() -> None:
    path = ROOT / "CHANGELOG.md"
    text = path.read_text(encoding="utf-8")
    marker = "`YYYY-MM-DD | 変更理由 | 対象ファイル | 戻す単位`\n\n"
    entry = (
        "2026-08-06 | 英語版のWhite Wing病院の主表記を日本語と英語で分け、英訳を自然な表現へ調整。日英のメタ説明文へWhite Wing病院を追加し、全ナビゲーションリンクの最小高さを44pxへ統一。language-switch専用CSSと重複指定を.nav aへ統合し、検査を追加 | index.html, en.html, assets/css/style.css, scripts/check_site.py, CHANGELOG.md | SquashコミットをRevert\n\n"
    text = replace_exact(text, marker, marker + entry)
    path.write_text(text, encoding="utf-8")


def main() -> None:
    update_html()
    update_css()
    update_checks()
    update_changelog()


if __name__ == "__main__":
    main()
